# -*- coding: utf-8 -*-
"""estimate_pi.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mig59Fm-Nq3wfxjdw4h8ZihreMKTZgjB
"""

import random
def estimate_pi(n):
  num_in_circle = 0
  num_in_square = 0
  for i in range(n):
    x = random.uniform(0,1)
    y = random.uniform(0,1)
    if x**2 + y**2 <= 1:
      num_in_circle += 1
    num_in_square += 1
  return 4 * (num_in_circle/num_in_square)

estimate_pi(1)

estimate_pi(10)

estimate_pi(100)

estimate_pi(1000)

estimate_pi(10000)

estimate_pi(1000000)

estimate_pi(100000000)